(** A tool being used by a device with the {!Device.Capability.Tablet_tool} capability.

    Tablet events generated by such a device are bound to a specific tool rather than coming from the device directly.
    Depending on the hardware it is possible to track the same physical tool across multiple {!Device.t} devices.
    See {!get_serial} for more details. *)

type t = [`Libinput_tablet_tool] Ctypes.structure Ctypes.ptr Droppable.t

module Type : sig
  type t =
    | Pen
    | Eraser
    | Brush
    | Pencil
    | Airbrush
    | Mouse
    | Lens
    | Totem
    | Unknown of int64

  val pp : t Fmt.t
end

val get_type : t -> Type.t

val get_tool_id: t -> int64 option
(** [get_tool_id t] returns the tool ID for a tool object, if any.

    This number identifies the specific type of the tool with more precision than the type returned in {!get_type}. *)

val has_pressure: t -> bool
val has_distance: t -> bool
val has_tilt: t -> bool
val has_rotation: t -> bool
val has_slider: t -> bool
val has_size: t -> bool
val has_wheel: t -> bool
val has_button: t -> int -> bool

val is_unique: t -> bool
(** [is_unique t] indicates whether the physical tool can be uniquely identified by libinput.

    If a tool can be uniquely identified, keeping a reference to the tool allows tracking the tool across
    proximity out sequences and across compatible tablets. See {!get_serial} for more details. *)

val get_serial: t -> int64 option
(** [get_serial t] returns the serial number of the tool, if any. *)

(** Tool configuration.

    See {{: https://wayland.freedesktop.org/libinput/doc/latest/api/group__config.html }}. *)
module Config : sig
  type 'a setting

  val set : t -> 'a setting -> 'a -> Config_status.t
  val get : t -> 'a setting -> 'a
  val get_default : t -> 'a setting -> 'a

  module Pressure_range : sig
    val is_available : t -> bool
    val set : t -> min:float -> max:float -> Config_status.t
    val get_minimum : t -> float
    val get_maximum : t -> float
    val get_default_minimum : t -> float
    val get_default_maximum : t -> float
  end

  module Eraser_button : sig
    module Mode : sig
      type t =
        | Default
        | Button
        | Unknown of int64

      val pp : t Fmt.t
    end

    val get_modes : t -> bool
    val mode : Mode.t setting
    val button : int setting
  end
end

val pp : t Fmt.t
